services:
  - type: web
    name: sensor-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sensor-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
    staticPublishPath: ./static
    staticBuildPath: ./static
    staticUrlPrefix: /static

databases:
  - name: sensor-db
    databaseName: sensor_db
    plan: free
    ipAllowList: []